config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    collection do
      get "/show_profile", to: "users#show_profile", as: "my_profile"
      get "/show_log", to: "users#show_log", as: "my_log"
      get "/coach_index", to: "users#coach_index", as: "coach_index"
      get "/trainee_index", to: "users#trainee_index", as: "trainee_index"
      post "/request_admin", to: "users#request_admin", as: "request_admin"
    end
    resources :posts, only: [:new, :create]
  end

  get "tags/:tag", to: "videos#index", as: :tag

  resources :posts, except: [:new, :create] do
    resources :videos, except: [:show, :index, :new, :edit, :destroy]
  end
  resources :videos, except: [:create, :update] do
    collection do
      get "/search", to: "videos#search", as: "search"
    end
    resources :comments, except: [:show, :index]
  end
  resources :home, only: [:about] do
    collection do
      get "/about", to: "home#about", as: "about"
    end
  end
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  after_create :set_coach, :welcome_email

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def address_changed?
    attrs = %w(city state zip)
    attrs.any? {|a| send "#{a}_changed?"}
  end

  def address
    [city, state, zip].compact.join(", ")
  end

  def set_coach
    self.update(admin: true) if ENV['COACH_EMAILS'].split(",").include?(email)
  end

  def welcome_email
    NewUserEmailMailer.notify_user(self).deliver
  end

  def self.search_coach(search)
    if search
      where('admin AND (username LIKE ? OR city LIKE ? OR state LIKE ? OR zip LIKE ? OR first_name LIKE ? OR last_name LIKE ?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      where(admin: true)
    end
  end

  def self.search_trainees(search)
    if search
      where('seeking_coach AND (username LIKE ? OR city LIKE ? OR state LIKE ? OR zip LIKE ? OR first_name LIKE ? OR last_name LIKE ?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" )
    else
      where(seeking_coach: true)
    end
  end

  has_many :posts, dependent: :destroy
  has_many :videos, through: :posts, dependent: :destroy
  has_many :comments

  validates :username, uniqueness: true, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /@/ }
  validates :password, presence: true
  validates :phone, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :zip, presence: true, numericality: true, format: { with: /[0-9]+/}
  validates :seeking_coach, presence: true
  validates :accept_email, presence: true
  validates :accept_phone, presence: true

  STATES = [
    [ "AL" , "AL" ],
    [ "AK" , "AK" ],
    [ "AZ" , "AZ" ],
    [ "AR" , "AR" ],
    [ "CA" , "CA" ],
    [ "CO" , "CO" ],
    [ "CT" , "CT" ],
    [ "DC" , "DC" ],
    [ "DE" , "DE" ],
    [ "FL" , "FL" ],
    [ "GA" , "GA" ],
    [ "HI" , "HI" ],
    [ "ID" , "ID" ],
    [ "IL" , "IL" ],
    [ "IN" , "IN" ],
    [ "IA" , "IA" ],
    [ "KS" , "KS" ],
    [ "KY" , "KY" ],
    [ "LA" , "LA" ],
    [ "ME" , "ME" ],
    [ "MA" , "MA" ],
    [ "MI" , "MI" ],
    [ "MN" , "MN" ],
    [ "MO" , "MO" ],
    [ "MS" , "MS" ],
    [ "MT" , "MT" ],
    [ "NE" , "NE" ],
    [ "NV" , "NV" ],
    [ "NH" , "NH" ],
    [ "NJ" , "NJ" ],
    [ "NM" , "NM" ],
    [ "NY" , "NY" ],
    [ "NC" , "NC" ],
    [ "ND" , "ND" ],
    [ "OH" , "OH" ],
    [ "OK" , "OK" ],
    [ "OR" , "OR" ],
    [ "PA" , "PA" ],
    [ "RI" , "RI" ],
    [ "SC" , "SC" ],
    [ "SD" , "SD" ],
    [ "TN" , "TN" ],
    [ "TX" , "TX" ],
    [ "UT" , "UT" ],
    [ "VA" , "VA" ],
    [ "VT" , "VT" ],
    [ "WA" , "WA" ],
    [ "WI" , "WI" ],
    [ "WV" , "WV" ],
    [ "WY" , "WY" ]
  ]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, :configure_permitted_parameters, if: :devise_controller?

  def coach_index
    if params[:search].nil?
      @coaches = User.where(admin: true).page(params[:page]).per_page(10).order("username")
    elsif params[:search].strip.length.zero?
      flash[:notice] = "Please enter search parameters!"
      @coaches = User.where(admin: true).page(params[:page]).per_page(10).order("username")
    elsif params[:search]
      final_search = params[:search].split.map(&:capitalize).join(" ")
      @coaches = User.search_coach(final_search).page(params[:page]).per_page(10).order("username")
    end
    @hash = Gmaps4rails.build_markers(@coaches) do |coach, marker|
      marker.lat coach.latitude
      marker.lng coach.longitude
      marker.infowindow "#{coach.first_name}#{coach.last_name} (#{coach.username}) | <a href=mailto:#{coach.email}>#{coach.email}</a> | #{coach.city}, #{coach.state} #{coach.zip}"
    end
  end

  def request_admin
    @user = current_user
    RequestAdminMailer.request_admin(@user).deliver
  end

  def trainee_index
    if params[:search].nil?
      @trainees = User.where(seeking_coach: true).page(params[:page]).per_page(10).order("username")
    elsif params[:search].strip.length.zero?
      flash[:notice] = "Please enter search parameters!"
      @trainees = User.where(seeking_coach: true).page(params[:page]).per_page(10).order("username")
    elsif params[:search]
      final_search = params[:search].split.map(&:capitalize).join(" ")
      @trainees = User.search_trainees(final_search).page(params[:page]).per_page(10).order("username")
    end
    @hash = Gmaps4rails.build_markers(@trainees) do |trainee, marker|
      marker.lat trainee.latitude
      marker.lng trainee.longitude
      marker.infowindow "#{trainee.first_name}#{trainee.last_name} (#{trainee.username}) | <a href=mailto:#{trainee.email}>#{trainee.email}</a> | #{trainee.city}, #{trainee.state} #{trainee.zip}"
    end
  end

  def show_profile
    @user = User.find(current_user.id)
  end

  def show_log
    @user = User.find(current_user.id)
    @posts = @user.posts.page(params[:page]).per_page(10)
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      @user.destroy
      flash[:notice] = "User Deleted!"
      redirect_to root_path
    else
      flash[:notice] = "Only owner may delete their profile"
      refresh :show_profile
    end
  end

  protected

  def authorize_user
    unless user_signed_in?
      flash[:notice] = "Please sign in first"
      redirect_to new_user_session_path
    end
  end

  def configure_permitted_parameters
    added_attrs = [
      :first_name,
      :last_name,
      :username,
      :email,
      :image,
      :phone,
      :state,
      :city,
      :zip,
      :seeking_coach,
      :accept_email,
      :accept_phone,
      :remember_me
    ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/views/users/_map.html.erb
<script src="//maps.google.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_API_KEY"]%>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="map" style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/users/coach_index.html.erb
<div class="input-group" style="margin: auto">
  <%= form_tag coach_index_users_path, method: 'get', class: 'navbar-form', role: 'search', id: "search-form" do %>
  <span class="input-group-btn">
    <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
    <%= text_field_tag :search, "", placeholder: "Search coaches", class: 'form-control' %>
  </span>
  <% end %>
</div>

<div class="text-center">
  <%= will_paginate @coaches %>
</div>

<div class="coaches text-center container" style="width:50%">
  <% @coaches.each do |coach| %>
    <div class="row panel highlight">
      <%= coach.username %>
    <p>
      <%= coach.first_name %> <%= coach.last_name %>
    </p>
      <%= coach.city %>, <%= coach.state %>
    <p>
      <%= link_to "Send Email", "mailto:#{coach.email}" %>
    </p>
    </div>
  <% end %>
</div>

<%= render "map" %>

app/views/users/show.html.erb
<%= @user.first_name %>
<%= @user.last_name %>
<%= @user.username %>
<%= @user.email %>
<%= @user.phone %>
<%= @user.country %>
<%= @user.state %>
<%= @user.city %>
<%= @user.zip %>

app/views/users/show_log.html.erb
<div class="text-center">
  <%= will_paginate @posts %>
</div>

<div class="show-log text-center container" style="width:50%">
  <div class="">
    <h3><%= @user.username %>'s Log</h3>
    <h3><%= link_to "Add new entry", new_user_post_path(@user) %></h3>
  </div>

  <div class="" >
    <% @posts.each do |post| %>
      <div class="row panel highlight" >
        <p>
          <%= link_to post.title, post_path(post) %>
          (<%= post.date %>)
        </p>
        <p>
          <%= link_to "Edit Post", edit_post_path(post) %> |
          <%= link_to "Delete Post", post, method: :delete, data: { confirm: "Are you sure?" } %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show_profile.html.erb
<div class="container panel profile-container highlight" style="width:100%; margin-top: 50px;">
  <div class="row">
    <div class=" col-sm-6 my-profile " style="width:50%">
      <p><%= @user.username %></p>
      <p><%= @user.first_name %> <%= @user.last_name %></p>
      <p><%= @user.email %></p>
      <p><%= @user.phone %></p>
      <p><%= @user.state %>, <%= @user.city %>, <%= @user.zip %></p>
      <p>
        <% unless @user.admin %>
          <%= button_to "Request Admin Status", request_admin_users_path %>
        <% end %>
      </p>
      <p>
        <% if @user.id == current_user.id %>
          <%= link_to("Edit Profile", edit_user_registration_path) %>
        <% end %>
      </p>
    </div>
    <div class=" col-sm-6 profile-pic " style="width:50%">
      <%= image_tag @user.image %>
    </div>
  </div>
</div>

app/views/users/trainee_index.html.erb
<div class="input-group" style="margin: auto">
  <%= form_tag trainee_index_users_path, method: 'get', class: 'navbar-form', role: 'search', id: "search-form" do %>
  <span class="input-group-btn">
    <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
    <%= text_field_tag :search, "", placeholder: "Search trainees", class: 'form-control' %>
  </span>
  <% end %>
</div>

<div class="text-center">
  <%= will_paginate @trainees %>
</div>

<div class="coaches text-center container" style="width:50%">
  <% @trainees.each do |trainee| %>
    <div class="row panel highlight">
      <%= trainee.username %><% if trainee.admin %>, SSC<% end %>
      <p>
        <%= trainee.first_name %>, <%= trainee.last_name %>
      </p>
      <%= trainee.city %>, <%= trainee.state %>
      <p>
        <%= link_to "Send Email", "mailto:#{trainee.email}" %>
      </p>
      <button>Send Text</button>
    </div>
  <% end %>
</div>

<%= render "map" %>