config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    collection do
      get "/show_profile", to: "users#show_profile", as: "my_profile"
      get "/show_log", to: "users#show_log", as: "my_log"
      get "/coach_index", to: "users#coach_index", as: "coach_index"
      get "/trainee_index", to: "users#trainee_index", as: "trainee_index"
      post "/request_admin", to: "users#request_admin", as: "request_admin"
    end
    resources :posts, only: [:new, :create]
  end

  get "tags/:tag", to: "videos#index", as: :tag

  resources :posts, except: [:new, :create] do
    resources :videos, except: [:show, :index, :new, :edit, :destroy]
  end
  resources :videos, except: [:create, :update] do
    collection do
      get "/search", to: "videos#search", as: "search"
    end
    resources :comments, except: [:show, :index]
  end
  resources :home, only: [:about] do
    collection do
      get "/about", to: "home#about", as: "about"
    end
  end
  root "home#index"
end

app/models/video.rb
class Video < ActiveRecord::Base
  after_create { validates_presence_of :user, :post }

  belongs_to :user
  belongs_to :post
  has_many :comments

  validates :title, presence: true
  acts_as_taggable

  validates :url, presence: true
  validates :url, format: { with: URI.regexp }, if: "url.present?"

  def self.search(search)
    videos = Video.tagged_with(search.to_s, :any => true)
    videos
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  before_action :authorize_user

  def index
    @videos = Video.all
  end

  def show
  end

  def authorize_user
    unless user_signed_in?
      flash[:notice] = "Please sign in or sign up in"\
      " order to view this video and its commentary"
      redirect_to root_path
    end
  end

  private

  def video_params
    # params.require(:video).permit(
    # list attributes here
    # )
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user, :configure_permitted_parameters, if: :devise_controller?

  def index
    if params[:tag]
      @videos = Video.tagged_with(params[:tag]).page(params[:page]).per_page(5).order(created_at: "desc")
    else
      @videos = Video.all.page(params[:page]).per_page(5).order(created_at: "desc")
    end
  end

  def search
    @results = Video.tagged_with(params[:search]) if params[:search]
  end

  def show
    @video = Video.find(params[:id])
    @user = @video.user
    @post = @video.post
    @comment = Comment.new
    @comments = @video.comments
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @video = Video.new(video_params)
    @video.user_id = @user.id
    @video.post_id = @post.id
    @video.embed_id = @video.url.split("=").last
    tags = params[:video][:tag_list][0].split(',')
    tags.each do |tag|
      @video.tag_list.add(tag)
    end
    if current_user == @post.user
      if @video.save
        flash[:notice] = "Video successfully created"
        redirect_to post_path(@post)
      else
        @errors = @video.errors.full_messages.join(", ")
        flash[:notice] = @errors
        render :"posts/show"
      end
    else
      flash[:notice] = "Only OP can upload videos"
      render :"posts/show"
    end
  end

  def edit
    @video = Video.find(params[:id])
    @post = @video.post
  end

  def update
    @video = Video.find(params[:id])
    @post = @video.post
    @video.update_attributes(video_params)
    if current_user == @video.user
      if @video.save
        flash[:notice] = "Video successfully updated!"
        redirect_to video_path(@video)
      else
        flash[:notice] = "Video was not updated."
        @errors = @video.errors.full_messages.join(", ")
        flash[:alert] = @errors
        render action: "edit"
      end
    else
      flash[:notice] = "Only OP can edit video"
      refresh :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    if current_user == @video.user
      @post = @video.post
      @user = @video.user
      @video.destroy
      redirect_to post_path(@post)
    end
  end

  private

  def video_params
    params.require(:video).permit(
      :title,
      :url,
      tag_list: []
    )
  end
end

app/views/videos/_comment_form.html.erb
<div class="container" style="width:50%">
  <% if current_user == @video.post.user || current_user.admin %>
    <%= form_for [@video, @comment] do |f| %>
      <div class="form-group row">
        <div class="">
          <%= f.label(:body, "Comment") %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="">
          <%= f.submit "Submit Comment", class: "form-control" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/videos/_new.html.erb
<h2 class="text-center" id="video-form"></h2>

<div class="container" style="width:35%">
  <% if current_user == @post.user || current_user.admin %>
    <div class="">
      <%= form_for [@post, @video] do |f| %>
        <div class="form-group row">
          <div class="">
            <%= f.label(:title, "Video Title") %></br >
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="">
            <%= f.label(:url, "Youtube Video Url") %> | <i class="fa fa-youtube" aria-hidden="true"></i></br >
            <%= f.text_field :url, class: "form-control" %>
          </div>

          <div class="">
            <%= f.label(:tag_list, "Tags (separated by commas)") %></br >
            <%= f.text_field :tag_list, multiple: true, class: "form-control" %>
          </div>

          <div class="">
            <%= f.submit "Submit Video", class: "form-control" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/videos/_search_bar.html.erb
<div class="input-group" style="margin: auto">
  <%= form_tag search_videos_path, method: 'get', class: 'navbar-form', role: 'search', id: "search-form" do %>
    <span class="input-group-btn">
      <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
      <%= text_field_tag :search, "", placeholder: "Search by video tag", class: 'form-control' %>
    </span>
  <% end %>
</div>

app/views/videos/_videos.html.erb
<div class="container">
  <div class="text-center">
    <%= will_paginate @videos %>
  </div>

  <% @videos.each do |video| %>
    <div class="row panel panel-default highlight video">

      <div class="col-sm-6 text-center panel">
        <p class="panel-heading">
          <%= link_to video.title, video_path(video) %>
        </p>
        <p class="panel-body">
          <%= content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{video.embed_id}") %>
        </p>
        <p class="panel-footer">
          <i class="fa fa-youtube" aria-hidden="true"></i> |
          Created by: <%= video.user.username %>, at: <%= video.created_at.strftime("%e, %b, %Y, %H:%M:%S %p") %></br>
          Tags: <%= raw video.tag_list.map { |t| link_to t, tag_path(t) }.join(", ") %>
        </p>
      </div>

      <div class="col-sm-6 video-index panel">
        <% unless video.comments.last.nil? %>
        <p class="panel-body">
          <%= video.comments.last.body %>
        </p>
        <p class="panel-footer">
          <i class="fa fa-comment" aria-hidden="true"></i> |
          Posted by: <%= video.comments.last.user.username %>, at: <%= video.comments.last.created_at %>
        </p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/videos/edit.html.erb
<div class="highlight">
  <%= render "new" %>
</div>

app/views/videos/index.html.erb
<%= render "search_bar" %>

<div id="videos">
  <%= render "videos" %>
</div>

<div class="" id="tag_cloud">
  <% tag_cloud Video.tag_counts.sort { |x, y| x.name <=> y.name }, %w[s m l] do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

app/views/videos/search.html.erb
<%= render "search_bar" %>

<div class="container">
  <% if @results.count > 1 %>
    <% s = "s" %>
  <% end %>
  <h3><%= @results.count %> Result<%= s %>:</h3>
  <% unless @results.empty? %>
    <% @results.each do |video| %>
      <div class="row panel panel-default">
        <div class="col-sm-6 text-center panel">
          <p class="panel-heading">
            <%= link_to video.title, video_path(video) %>
          </p>
          <p class="panel-body">
            <%= content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{video.embed_id}") %>
          </p>
          <p class="panel-footer">
            <i class="fa fa-youtube" aria-hidden="true"></i> | 
            Created by: <%= video.user.username %>, at: <%= video.created_at.strftime("%e, %b, %Y, %H:%M:%S %p") %></br>
            Tags: <%= raw video.tag_list.map { |t| link_to t, tag_path(t) }.join(", ") %>
          </p>
        </div>

        <div class="col-sm-6 video-index panel">
          <% unless video.comments.last.nil? %>
          <p class="panel-body">
            <%= video.comments.last.body %>
          </p>
          <p class="panel-footer">
            <i class="fa fa-comment" aria-hidden="true"></i> |
            Posted by: <%= video.comments.last.user.username %>, at: <%= video.comments.last.created_at %>
          </p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to("Back to Index", videos_path) %>

app/views/videos/show.html.erb
<div class="container text-center" style="width:50%; padding-top:50px;">
  <div class="video-show panel">
    <i class="fa fa-youtube" aria-hidden="true"></i> | <%= @video.title %>
    <p>
      <%= content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{@video.embed_id}") %>
    </p>
    <p>
      Tags: <%= raw @video.tag_list.map { |t| link_to t, tag_path(t) }.join(", ") %>
    </p>
    <% if current_user == @video.user %>
      <%= link_to "Edit Video", edit_video_path(@video) %> |
      <%= link_to "Delete Video", video_path(@video), method: :delete, data: { confirm: "Are you sure?" } %> |
    <% end %>
    <% if current_user == @video.user %>
      <%= link_to("Back to Log", post_path(@post)) %> |
    <% end %>
    <%= link_to("Back to Index", videos_path) %>
  </div>
</div>


<%= render "comment_form" %>

<div class="comments text-center">
  <% unless @comments.nil? %>
  <h3 class="text-center">Comments</h3>
    <% @comments.each do |comment| %>
      <div class="comment highlight panel">
        <p class="panel-body">
          <%= comment.body %>
        </p>
        <p class="panel-footer">
          <i class="fa fa-comment" aria-hidden="true"></i> |
          Posted by: <%= comment.user.username %>, at: <%= comment.created_at %>
        </p>
        <% if current_user == comment.user %>
          <%= link_to "Edit Comment", edit_video_comment_path(comment.video, comment) %> |
          <%= link_to "Delete Comment", video_comment_path(@video, comment), method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>