config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    collection do
      get "/show_profile", to: "users#show_profile", as: "my_profile"
      get "/show_log", to: "users#show_log", as: "my_log"
      get "/coach_index", to: "users#coach_index", as: "coach_index"
      get "/trainee_index", to: "users#trainee_index", as: "trainee_index"
      post "/request_admin", to: "users#request_admin", as: "request_admin"
    end
    resources :posts, only: [:new, :create]
  end

  get "tags/:tag", to: "videos#index", as: :tag

  resources :posts, except: [:new, :create] do
    resources :videos, except: [:show, :index, :new, :edit, :destroy]
  end
  resources :videos, except: [:create, :update] do
    collection do
      get "/search", to: "videos#search", as: "search"
    end
    resources :comments, except: [:show, :index]
  end
  resources :home, only: [:about] do
    collection do
      get "/about", to: "home#about", as: "about"
    end
  end
  root "home#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :videos, dependent: :destroy
  has_many :comments, through: :video

  validates :title, presence: true
  validates :date, presence: true
  validates :body, presence: true

  after_create { validates_presence_of :user }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, :configure_permitted_parameters, if: :devise_controller?

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @user = current_user
    @post = Post.new(post_params)
    @post.user = @user
    if @post.save
      flash[:notice] = "Log entry submitted"
      redirect_to post_path(@post)
    else
      flash[:notice] = @post.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @videos = @post.videos
    @video = Video.new
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user == @post.user
      @post.destroy
      redirect_to my_log_users_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    if current_user == @post.user
      if @post.save
        flash[:notice] = "Post successfully updated!"
        redirect_to post_path(@post)
      else
        flash[:notice] = "Post was not updated."
        @errors = @post.errors.full_messages.join(", ")
        flash[:alert] = @errors
        render action: "edit"
      end
    else
      flash[:notice] = "Only OP can edit post"
      refresh :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(
    :title,
    :date,
    :body,
    :user
    )
  end
end

app/views/posts/_form.html.erb
<div class="container post-form">
  <%= form_for [@user, @post] do |f| %>
    <div class="form-group row">
      <%= f.label(:title, "Title") %></br >
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label(:date, "Date") %></br >
      <%= f.date_field :date, value: Date.today.strftime("%m/%d/%Y"), class: "form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label(:body, "Body") %></br >
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div type="submit row" style="margin:auto">
      <%= f.submit("Submit") %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h2 class="text-center">Edit Post</h2>

<%= render "form" %>

app/views/posts/new.html.erb
<%= render "form" %>

<div class="text-center">
  <%= link_to("Back", my_log_users_path) %>
</div>

app/views/posts/show.html.erb
<div class="container post-show">
  <div class="text-center panel highlight" style="margin:auto">
    <p>
      <%= @post.title %> (<%= @post.date %>)
    </p>
    <p>
      <%= @post.body %>
    </p>
    <% if current_user == @post.user %>
      <%= link_to "Edit Post", edit_post_path(@post) %> |
      <%= link_to "Delete Post", @post, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>

  <h3 class="text-center">Videos of this session</h3>

  <div class="text-center highlight" style="margin:auto">
  <% @videos.each do |video| %>
    <div class="panel">
      <%= link_to video.title, video_path(video) %>
      <% if current_user == video.user %>
        <p>
          <%= link_to "Edit Video", edit_video_path(video) %> |
          <%= link_to "Delete Video", video_path(video), method: :delete, data: { confirm: "Are you sure?" } %>
        </p>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

<div class="highlight panel">
  <%= render "./videos/new" %>
  <div class="text-center">
    <%= link_to("Back", my_log_users_path) %>
  </div>
</div>