config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    collection do
      get "/show_profile", to: "users#show_profile", as: "my_profile"
      get "/show_log", to: "users#show_log", as: "my_log"
      get "/coach_index", to: "users#coach_index", as: "coach_index"
      get "/trainee_index", to: "users#trainee_index", as: "trainee_index"
      post "/request_admin", to: "users#request_admin", as: "request_admin"
    end
    resources :posts, only: [:new, :create]
  end

  get "tags/:tag", to: "videos#index", as: :tag

  resources :posts, except: [:new, :create] do
    resources :videos, except: [:show, :index, :new, :edit, :destroy]
  end
  resources :videos, except: [:create, :update] do
    collection do
      get "/search", to: "videos#search", as: "search"
    end
    resources :comments, except: [:show, :index]
  end
  resources :home, only: [:about] do
    collection do
      get "/about", to: "home#about", as: "about"
    end
  end
  root "home#index"
end

app/views/layouts/_footer.html.erb
<div class="footer container">
  <div class="row links text-center" style="margin: 35px">
    <div class="col-sm-6">
      <p><%= link_to 'Starting Strength Coaches Association', "http://startingstrength.org", { class: "footer-link" } %></p>
      <p><%= link_to 'Starting Strength', "http://startingstrength.com", { class: "footer-link" }  %></p>
      <p><%= link_to "Contact Us", "mailto:coachrwebapp@gmail.com", { class: "footer-link" }  %></p>
    </div>

    <div class="col-sm-2">
      <%= link_to '<i id="github" class="icon fa fa-2x fa-github" aria-hidden="true"></i>'.html_safe, "https://github.com/noahmilstein/breakable_toy" %>
    </div>
    <div class="col-sm-2">
      <%= link_to '<i id="facebook" class="icon fa fa-2x fa-facebook" aria-hidden="true"></i>'.html_safe, "https://www.facebook.com/Starting-Strength-The-Aasgaard-Company-142424022490628/" %>
    </div>
    <div class="col-sm-2">
      <%= link_to '<i id="instagram" class="icon fa fa-2x fa-instagram" aria-hidden="true"></i>'.html_safe, "https://www.instagram.com/startingstrength/?hl=en" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BreakableToy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  </head>

  <body>
    <div class="main">
      <nav id="app">
        <% if user_signed_in? %>
          <div class="">
            <%= link_to "Home", root_path %> |
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> |
            <%= link_to "My Profile", my_profile_users_path %> |
            <%= link_to "My Log", my_log_users_path %> |
            <%= link_to "Video Index", videos_path %> |
            <% if !current_user.admin %>
              <%= link_to "Coach Index", coach_index_users_path %> |
            <% else %>
              <%= link_to "Trainee Index", trainee_index_users_path %> |
            <% end %>
            <% if current_user.admin %>
              Logged in as coach: <strong> <%= current_user.username %> <%= image_tag current_user.image.small_profile_picture %></strong>
            <% else %>
              Logged in as <strong> <%= current_user.username %> <%= image_tag current_user.image.small_profile_picture %></strong>
            <% end %>
          </div>
        <% else %>
          <div class="">
            <%= link_to "Home", root_path %> |
            <%= link_to "Sign Up", new_user_registration_path %> |
            <%= link_to "Sign In", new_user_session_path %>
          </div>
        <% end %>
      </nav>
    <p class="notice flash-box"><%= notice %></p>
    <p class="alert flash-box"><%= alert %></p>
    <%= yield %>
    </div>
    <footer class="navbar-fixed-bottom">
      <%= render "./layouts/footer" %>
    </footer>
  </body>
</html>